project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_ACCESS_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: "app/src/main/res/values/strings.xml"
    translation: "src/main/res/values-%two_letters_code%/strings.xml"
    dest: "strings.xml"